// {
//   '$uuid': 'fa528ef0-4811-45e9-be4e-fbf2b82bed78',
//   '$etag': '2023-09-25T04:43:04Z',
//   '$actxUser': 'ADMIN',
//   '$actxLogin': 'ADMIN',
//   '$actxFolder': 'SEED',
//   '$actxSolution': 'X3V12',
//   '$actxLan': 'ENG',
//   '$actxLanIso': 'en-US',
//   '$actxNbLeg': '21',
//   '$actxLegCur': '',
//   BPAINVNAM: 'Rovi',
//   BPAPYRNAM: 'Rovi',
//   ABCCLS: 1,
//   ACCCOD: 'LOCAL',
//   BCGCOD: 'ES',
//   BCGCOD_REF: { '$title': 'Spanish', '$description': 'Spanish customers' },
//   BPAINV: '001',
//   BPAINV_REF: { '$description': 'Rovi', '$title': '' },
//   BPAPYR: '001',
//   BPAPYR_REF: { '$description': 'Rovi', '$title': '' },
//   BPCBPSNUM: '',
//   BPCCDTISR: '',
//   BPCCDTISR_REF: { '$title': '' },
//   BPCGRU: 'ES007',
//   BPCINV: 'ES007',
//   BPCNUM: 'ES007',
//   BPCPYR: 'ES007',
//   BPCPYR_REF: { '$title': 'Server Sis', '$description': 'Server Sistemas' },
//   BPCRSK: 'ES007',
//   BPCSHO: 'Server Sis',
//   BPCSNCDAT: '2025-01-28',
//   BPCSTA: true,
//   BPCTYP: 1,
//   BPCBPD: [
//     {
//       '$uuid': '42029328-224a-4d5f-8eec-3d5ba01a2321',
//       BPC_BPD_BPAADD: '001',
//       BPC_BPD_BPAADD_REF: [Object],
//       BP__BPD_BPAADDNAM: 'Rovi',
//       BPCLOC: '',
//       BPCLOC_REF: [Object],
//       BPC_BPD_BPDADDFLG: true,
//       BPTNUM: 'ES201',
//       BPTNUM_REF: [Object],
//       CLADLVTEX: null,
//       CLAPRPTEX: null,
//       BPCBPDC_BPDNAM: [Array],
//       BPCBPDC_REP: [Array],
//       DAYLTI: 2,
//       DLVPIO: 1,
//       DLVTEX: '',
//       DRN: 1,
//       EECICT: 'EXW',
//       EECICT_REF: [Object],
//       EECINCRAT: 0,
//       EECLOC: 2,
//       BPC_BPD_EECNUM: '',
//       ENAFLG: true,
//       FFWADD: '',
//       FFWADD_REF: [Object],
//       FFWNUM: '',
//       FFWNUM_REF: [Object],
//       ICTCTY: '',
//       BPC_BPD_LAN: 'SPA',
//       BPC_BPD_LAN_REF: [Object],
//       MDL: '3',
//       MDL_REF: [Object],
//       NDEFLG: true,
//       NPRFLG: true,
//       PRPTEX: '',
//       RCPFCY: '',
//       RCPFCY_REF: [Object],
//       SCOLOC: '',
//       SCOLOC_REF: [Object],
//       STOFCY: '',
//       STOFCY_REF: [Object],
//       UVYCOD: '',
//       UVYDAY1: true,
//       UVYDAY2: true,
//       UVYDAY3: true,
//       UVYDAY4: true,
//       UVYDAY5: true,
//       UVYDAY6: false,
//       UVYDAY7: false,
//       BPC_BPD_VACBPR: '',
//       BPC_BPD_VACBPR_REF: [Object],
//       BPC_BPD_VACBPR_LEG: '',
//       BPC_BPD_VACBPR_LEG_REF: [Object],
//       '$properties': [Object]
//     },
//     {
//       '$uuid': 'ee26e2e9-7473-43a1-884a-d47e443d8ea2',
//       BPC_BPD_BPAADD: '002',
//       BPC_BPD_BPAADD_REF: [Object],
//       BP__BPD_BPAADDNAM: 'Coruña',
//       BPCLOC: '',
//       BPCLOC_REF: [Object],
//       BPC_BPD_BPDADDFLG: false,
//       BPTNUM: '',
//       BPTNUM_REF: [Object],
//       CLADLVTEX: null,
//       CLAPRPTEX: null,
//       BPCBPDC_BPDNAM: [Array],
//       BPCBPDC_REP: [Array],
//       DAYLTI: 3,
//       DLVPIO: 1,
//       DLVTEX: '',
//       DRN: 2,
//       EECICT: 'EXW',
//       EECICT_REF: [Object],
//       EECINCRAT: 0,
//       EECLOC: 2,
//       BPC_BPD_EECNUM: '',
//       ENAFLG: true,
//       FFWADD: '',
//       FFWADD_REF: [Object],
//       FFWNUM: '',
//       FFWNUM_REF: [Object],
//       ICTCTY: '',
//       BPC_BPD_LAN: 'SPA',
//       BPC_BPD_LAN_REF: [Object],
//       MDL: '3',
//       MDL_REF: [Object],
//       NDEFLG: true,
//       NPRFLG: true,
//       PRPTEX: '',
//       RCPFCY: '',
//       RCPFCY_REF: [Object],
//       SCOLOC: '',
//       SCOLOC_REF: [Object],
//       STOFCY: '',
//       STOFCY_REF: [Object],
//       UVYCOD: '',
//       UVYDAY1: true,
//       UVYDAY2: true,
//       UVYDAY3: true,
//       UVYDAY4: true,
//       UVYDAY5: true,
//       UVYDAY6: false,
//       UVYDAY7: false,
//       BPC_BPD_VACBPR: '',
//       BPC_BPD_VACBPR_REF: [Object],
//       BPC_BPD_VACBPR_LEG: '',
//       BPC_BPD_VACBPR_LEG_REF: [Object],
//       '$properties': [Object]
//     },
//     {
//       '$uuid': '03fe50c2-6642-463c-858c-4dd15f8611eb',
//       BPC_BPD_BPAADD: '003',
//       BPC_BPD_BPAADD_REF: [Object],
//       BP__BPD_BPAADDNAM: 'Bilbao',
//       BPCLOC: '',
//       BPCLOC_REF: [Object],
//       BPC_BPD_BPDADDFLG: false,
//       BPTNUM: '',
//       BPTNUM_REF: [Object],
//       CLADLVTEX: null,
//       CLAPRPTEX: null,
//       BPCBPDC_BPDNAM: [Array],
//       BPCBPDC_REP: [Array],
//       DAYLTI: 2,
//       DLVPIO: 1,
//       DLVTEX: '',
//       DRN: 3,
//       EECICT: 'EXW',
//       EECICT_REF: [Object],
//       EECINCRAT: 0,
//       EECLOC: 2,
//       BPC_BPD_EECNUM: '',
//       ENAFLG: true,
//       FFWADD: '',
//       FFWADD_REF: [Object],
//       FFWNUM: '',
//       FFWNUM_REF: [Object],
//       ICTCTY: '',
//       BPC_BPD_LAN: 'SPA',
//       BPC_BPD_LAN_REF: [Object],
//       MDL: '3',
//       MDL_REF: [Object],
//       NDEFLG: true,
//       NPRFLG: true,
//       PRPTEX: '',
//       RCPFCY: '',
//       RCPFCY_REF: [Object],
//       SCOLOC: '',
//       SCOLOC_REF: [Object],
//       STOFCY: '',
//       STOFCY_REF: [Object],
//       UVYCOD: '',
//       UVYDAY1: true,
//       UVYDAY2: true,
//       UVYDAY3: true,
//       UVYDAY4: true,
//       UVYDAY5: true,
//       UVYDAY6: true,
//       UVYDAY7: false,
//       BPC_BPD_VACBPR: '',
//       BPC_BPD_VACBPR_REF: [Object],
//       BPC_BPD_VACBPR_LEG: '',
//       BPC_BPD_VACBPR_LEG_REF: [Object],
//       '$properties': [Object]
//     }
//   ],
//   BETFCY: false,
//   BPCBPRBPA: [
//     {
//       '$uuid': 'a88dd57f-b0ba-4d46-84a2-333772fa6919',
//       ADRVAL: false,
//       BPR_BPA_BPAADD: '001',
//       BPR_BPA_BPAADD_REF: [Object],
//       BPAADDLIG1: 'C/ Baleares',
//       BPAADDLIG2: 'Edificio Torres',
//       BPAADDLIG3: '',
//       BPADEFFLG: true,
//       BPADES: 'Rovi',
//       BPR_BPA_BPANUM: 'ES007',
//       BPR_BPA_BPATYP: 1,
//       BPCBPRBPACOLTEL: [Array],
//       BPCBPRBPACOLWEB: [Array],
//       BPC_BPA_CRY: 'ES',
//       BPC_BPA_CRY_REF: [Object],
//       CRYNAM: 'España',
//       CTY: 'MADRID',
//       EXTNUM: '',
//       FCYWEB: '',
//       POSCOD: '28029',
//       POSCOD_REF: [Object],
//       SAT: 'MADRID',
//       SAT_REF: [Object],
//       '$properties': [Object]
//     },
//     {
//       '$uuid': '48e0e798-3ee2-416a-8fde-9d300629408b',
//       ADRVAL: false,
//       BPR_BPA_BPAADD: '002',
//       BPR_BPA_BPAADD_REF: [Object],
//       BPAADDLIG1: 'Comandante Barja, 3 bajo',
//       BPAADDLIG2: '',
//       BPAADDLIG3: '',
//       BPADEFFLG: false,
//       BPADES: 'Coruña',
//       BPR_BPA_BPANUM: 'ES007',
//       BPR_BPA_BPATYP: 1,
//       BPCBPRBPACOLTEL: [Array],
//       BPCBPRBPACOLWEB: [Array],
//       BPC_BPA_CRY: 'ES',
//       BPC_BPA_CRY_REF: [Object],
//       CRYNAM: 'España',
//       CTY: 'A CORUÑA',
//       EXTNUM: '',
//       FCYWEB: '',
//       POSCOD: '15004',
//       POSCOD_REF: [Object],
//       SAT: 'A CORUÑA',
//       SAT_REF: [Object],
//       '$properties': [Object]
//     },
//     {
//       '$uuid': 'ee241431-1061-40da-9f56-494e4fa626c1',
//       ADRVAL: false,
//       BPR_BPA_BPAADD: '003',
//       BPR_BPA_BPAADD_REF: [Object],
//       BPAADDLIG1: 'General Concha, 28 bis',
//       BPAADDLIG2: '',
//       BPAADDLIG3: '',
//       BPADEFFLG: false,
//       BPADES: 'Bilbao',
//       BPR_BPA_BPANUM: 'ES007',
//       BPR_BPA_BPATYP: 1,
//       BPCBPRBPACOLTEL: [Array],
//       BPCBPRBPACOLWEB: [Array],
//       BPC_BPA_CRY: 'ES',
//       BPC_BPA_CRY_REF: [Object],
//       CRYNAM: 'España',
//       CTY: 'BILBAO',
//       EXTNUM: '',
//       FCYWEB: '',
//       POSCOD: '48010',
//       POSCOD_REF: [Object],
//       SAT: 'BILBAO',
//       SAT_REF: [Object],
//       '$properties': [Object]
//     }
//   ],
//   BPCFLG: true,
//   BPRACC: false,
//   BPRFBDMAG: false,
//   BPRLOG: 'S.A.',
//   BPSFLG: false,
//   BPTFLG: false,
//   CRN: 'A28599033',
//   CRY: 'ES',
//   CRY_REF: { '$title': 'Spain', '$description': 'Spain' },
//   BPC_BPR_CUR: 'EUR',
//   BPC_BPR_CUR_REF: {
//     '$title': 'Euro',
//     '$description': 'EURO',
//     '$symbol': '€',
//     '$scale': 2,
//     '$precision': 13
//   },
//   BPCBPRC_BPRNAM: [ 'Server Sistemas' ],
//   DOOFLG: false,
//   EECNUM: 'ESA28599033',
//   FCY: '',
//   FCY_REF: { '$title': '' },
//   LAN: 'SPA',
//   LAN_REF: { '$title': 'Spanish', '$description': 'Spanish' },
//   LEGETT: false,
//   NAF: '',
//   PPTFLG: false,
//   PRVFLG: false,
//   REPFLG: false,
//   '$properties': {
//     REPCUR: { '$x3Format': '' },
//     CUR: { '$x3Format': '' },
//     BPCNUM: { '$isMandatory': true },
//     LAN: { '$isMandatory': true },
//     BPC_BPR_CUR: { '$x3Format': '', '$isMandatory': true }
//   },
//   BUS: 'C1',
//   BUS_REF: { '$title': 'Distrib.', '$description': 'Distribution' },
//   CHGTYP: 1,
//   CLAINVTEX: null,
//   CLAORDTEX1: null,
//   COMCAT: 1,
//   COTCHX: '',
//   COTPITRQD: 0,
//   CUR: 'EUR',
//   CUR_REF: {
//     '$title': 'Euro',
//     '$description': 'EURO',
//     '$symbol': '€',
//     '$scale': 2,
//     '$precision': 13
//   },
//   BPCC_DIE: [
//     {
//       '$uuid': '17fbddac-893a-5b40-812e-60d9cdf8970d',
//       CCE: '',
//       CCE_REF: [Object],
//       DIE: 'CCT',
//       DIE_REF: [Object]
//     },
//     {
//       '$uuid': '15a552d7-5cec-b944-921d-424f0dfe3afa',
//       CCE: '',
//       CCE_REF: [Object],
//       DIE: 'PRJ',
//       DIE_REF: [Object]
//     },
//     {
//       '$uuid': 'bb76827b-796e-e849-b36b-f75f779eb734',
//       CCE: '',
//       CCE_REF: [Object],
//       DIE: 'PRO',
//       DIE_REF: [Object]
//     },
//     {
//       '$uuid': 'facab5d9-f6d4-6643-91cb-5e46189c61e0',
//       CCE: 'SERVICE',
//       CCE_REF: [Object],
//       DIE: 'MAR',
//       DIE_REF: [Object]
//     }
//   ],
//   BPCC_INVDTAAMT: [
//     {
//       '$uuid': '704bfcbb-c45e-5442-988a-ca75bbd2fc06',
//       INVDTA: 1,
//       INVDTAAMT: 0,
//       INVDTACUR: '',
//       INVDTACUR_REF: [Object],
//       INVDTADES: 'Discount %',
//       INVDTATYP: 3
//     },
//     {
//       '$uuid': '057b0399-4ecc-6649-bd88-c960fdba6275',
//       INVDTA: 2,
//       INVDTAAMT: 0,
//       INVDTACUR: 'EUR',
//       INVDTACUR_REF: [Object],
//       INVDTADES: 'Freight',
//       INVDTATYP: 1,
//       '$properties': [Object]
//     },
//     {
//       '$uuid': '4f7c0c88-d9bc-b84d-910a-ff832238c0a5',
//       INVDTA: 3,
//       INVDTAAMT: 0,
//       INVDTACUR: 'EUR',
//       INVDTACUR_REF: [Object],
//       INVDTADES: 'Insurance',
//       INVDTATYP: 1,
//       '$properties': [Object]
//     }
//   ],
//   BPCC_TSCCOD: [
//     {
//       '$uuid': '8b9ddd16-c97e-f04c-8eb2-2a14cbbe56fc',
//       TSCCOD: '700',
//       TSCCOD_REF: [Object],
//       TSCCODADI: 31
//     },
//     {
//       '$uuid': '35fbc9cc-e3e5-d743-bbe4-eb140971cd26',
//       TSCCOD: '710',
//       TSCCOD_REF: [Object],
//       TSCCODADI: 32
//     },
//     {
//       '$uuid': '1cecef1f-da5d-5246-be7f-e62ecfd33a72',
//       TSCCOD: 'EUR',
//       TSCCOD_REF: [Object],
//       TSCCODADI: 33
//     },
//     {
//       '$uuid': '39aead2f-714f-f742-9c78-dcd6c75b9236',
//       TSCCOD: '',
//       TSCCOD_REF: [Object],
//       TSCCODADI: 0
//     },
//     {
//       '$uuid': '557d8d10-f505-8a48-8287-beb3a0bf9a67',
//       TSCCOD: '',
//       TSCCOD_REF: [Object],
//       TSCCODADI: 0
//     }
//   ],
//   DEP: '',
//   DEP_REF: { '$title': '' },
//   DEP_LEG: '',
//   DEP_LEG_REF: { '$title': '' },
//   DIA: '',
//   DME: 1,
//   DUDCLC: 1,
//   FCTNUM: '',
//   FCTNUM_REF: { '$title': '' },
//   FREINV: 1,
//   FUPMINAMT: 0,
//   FUPTYP: 3,
//   GRP: 'ES01',
//   GRP_REF: { '$title': 'Spain', '$description': 'Spanish customer group' },
//   IME: 1,
//   INVPER: 1,
//   INVTEX: '',
//   LNDAUZ: false,
//   OCNFLG: false,
//   ODL: false,
//   ORDCLE: true,
//   ORDTEX: '',
//   ORIPPT: 'E1',
//   ORIPPT_REF: { '$title': 'Customer', '$description': 'Customer lead' },
//   OSTCTL: 1,
//   PAYBAN: '',
//   PITCDT: 0,
//   PITCPT: 0,
//   PRITYP: 1,
//   PTE: 'CH30NET',
//   PTE_REF: {
//     '$title': '30 Days',
//     '$description': 'Check 30 days date of Invoice'
//   },
//   PTE_LEG: '',
//   PTE_LEG_REF: { '$title': '' },
//   SOIPER: 1,
//   TOTPIT: 0,
//   TPMCOD: '',
//   UVYCOD2: '',
//   VACBPR: 'NAC',
//   VACBPR_REF: { '$title': 'Domectic', '$description': 'Domestic Spain' },
//   VACBPR_LEG: 'SPA',
//   VACBPR_LEG_REF: { '$title': 'Spanish', '$description': 'Spain' },
//   VATEXN: '',
//   BPCPITDEB: 0,
//   CDTISR: 90000.87,
//   CDTISRDAT: '2026-11-30',
//   NULPIO: false,
//   ORDMINAMT: 0,
//   OST: 126997.2,
//   OSTAUZ: 90000.87,
//   REPCUR: 'EUR',
//   REPCUR_REF: {
//     '$title': 'Euro',
//     '$description': 'EURO',
//     '$symbol': '€',
//     '$scale': 2,
//     '$precision': 13
//   }
// }
